apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cae-webapp-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.cae.anstat
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cae-webapp-service
            port:
              number: 80