apiVersion: v1
kind: Service
metadata:
  name: cae-webapp-service
  namespace: production
spec:
  selector:
    app: cae-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP